-- AlterEnum
ALTER TYPE "Action" ADD VALUE 'PRIOR_AUTHORIZATION';

-- AlterEnum
ALTER TYPE "EncounterType" ADD VALUE 'PRIOR_AUTHORIZATION';

-- AlterTable
ALTER TABLE "Insurance" ALTER COLUMN "insuranceStartDate" SET DEFAULT '''1900-01-01T00:00:00.000Z''';

-- AlterTable
ALTER TABLE "Patient" ALTER COLUMN "dob" SET DEFAULT '''1900-01-01T00:00:00.000Z''';
